import ajax from 'utils/ajax';

let actions = {};
/*eslint-disable*/
const mockData = {
    'RECORDS': [
        {
            'id': 1902,
            'country': 'US',
            'android_version': null,
            'cu': '5056U-2PLCIN1',
            'imei': '35155*****99808',
            'model': '5056U',
            'create_time': '2018\/12\/9 02:32:39',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，10 = extremely likely)',
            'answer1': 'Stars:5',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'Because it has no new update and not working properly.it gets switch off sometimes on calling alson',
            'question3': 'Which features would make you give the device a better rating? (Up to 5 max)',
            'answer3': '\r\nBetter external materials and textures\r\nLess weight \/ thickness\r\nEasier to use software\r\nBetter screen display\r\nBetter camera quality?'
        },
        {
            'id': 1903,
            'country': 'US',
            'android_version': null,
            'cu': '8050D-2JALAVL-3',
            'imei': '35412*****97760',
            'model': '8050D',
            'create_time': '2018\/12\/9 02:26:17',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，11 = extremely likely)',
            'answer1': 'Stars:2',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 6 max)',
            'answer3': '\r\nMore stable software'
        },
        {
            'id': 1904,
            'country': 'US',
            'android_version': null,
            'cu': '5023E-2AALBN1',
            'imei': '35979*****34815',
            'model': '5023E',
            'create_time': '2018\/12\/9 02:23:34',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，12 = extremely likely)',
            'answer1': 'Stars:2',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': "Memory too low. Cannot and doesn't save automatically on SD card. Slow response on command and poor quality photo..",
            'question3': 'Which features would make you give the device a better rating? (Up to 7 max)',
            'answer3': '\r\nLess weight \/ thickness\r\nBetter screen display\r\nHigher storage capacity\r\nMore processing power\r\nBetter camera quality?'
        },
        {
            'id': 1905,
            'country': 'GB',
            'android_version': null,
            'cu': 'null',
            'imei': 'null',
            'model': '5045X',
            'create_time': '2018\/12\/9 02:21:12',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，13 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'Rie di poesia e non pasta sposa e ora posso venire so che appare in un aperitivo con s e notizie cosa sta succedendo sposa sopra posso postare posso aiutarti piacere ai sensi',
            'question3': 'Which features would make you give the device a better rating? (Up to 8 max)',
            'answer3': '\r\nBetter after sales service'
        },
        {
            'id': 1906,
            'country': 'US',
            'android_version': null,
            'cu': '4034F-2FALPK1',
            'imei': 'null',
            'model': '4034F',
            'create_time': '2018\/12\/9 01:52:23',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，14 = extremely likely)',
            'answer1': 'Stars:1',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'No like n',
            'question3': 'Which features would make you give the device a better rating? (Up to 9 max)',
            'answer3': null
        },
        {
            'id': 1907,
            'country': 'GB',
            'android_version': null,
            'cu': '5045D-2AALTH1',
            'imei': 'null',
            'model': '5045D',
            'create_time': '2018\/12\/9 01:35:45',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，15 = extremely likely)',
            'answer1': 'Stars:4',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 10 max)',
            'answer3': '\r\nMore stable software\r\nUpgradable Android version\r\nBetter screen display\r\nBetter audio quality\r\nBetter camera quality?'
        },
        {
            'id': 1908,
            'country': 'GB',
            'android_version': null,
            'cu': '4034X-2GTWGB1',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/9 01:25:27',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，16 = extremely likely)',
            'answer1': 'Stars:0',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'Only got small amount of spacen',
            'question3': 'Which features would make you give the device a better rating? (Up to 11 max)',
            'answer3': '\r\nHigher storage capacity'
        },
        {
            'id': 1909,
            'country': 'GB',
            'android_version': null,
            'cu': '5051X-2DALGB1',
            'imei': '35736*****15353',
            'model': '5051X',
            'create_time': '2018\/12\/9 01:12:58',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，17 = extremely likely)',
            'answer1': 'Stars:2',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 12 max)',
            'answer3': null
        },
        {
            'id': 1910,
            'country': 'US',
            'android_version': null,
            'cu': '8050E-2CALPH4',
            'imei': '01457*****37553',
            'model': '8050E',
            'create_time': '2018\/12\/9 01:09:59',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，18 = extremely likely)',
            'answer1': 'Stars:3',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 13 max)',
            'answer3': '\r\nBetter external materials and textures\r\nEasier to use software\r\nUpgradable Android version\r\nBetter screen display\r\nHigher storage capacity'
        },
        {
            'id': 1911,
            'country': 'US',
            'android_version': 'v7.0.1.2.0170.0',
            'cu': '5026D-2AOFUS1',
            'imei': '35344*****11334',
            'model': '5026D',
            'create_time': '2018\/12\/9 01:01:29',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，19 = extremely likely)',
            'answer1': 'Stars:7',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nUpgradable Android version\r\nBetter screen display\r\nHigher storage capacity\r\nBattery with longer duration\r\nBetter audio quality',
            'question3': 'Which features would make you give the device a better rating? (Up to 14 max)',
            'answer3': null
        },
        {
            'id': 1912,
            'country': 'AU',
            'android_version': null,
            'cu': '9003X-2AC9PC1',
            'imei': '35621*****56518',
            'model': '9003X',
            'create_time': '2018\/12\/9 00:59:25',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，20 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'Absolutely better for users,   while all functions and app working well with effective processing speed. Any one can go for it with out criticism. The designer of this phone meet the standard.',
            'question3': 'Which features would make you give the device a better rating? (Up to 15 max)',
            'answer3': '\r\nUpgradable Android version'
        },
        {
            'id': 1913,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0177.0',
            'cu': '4034X-2AE8GBA',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/9 00:49:07',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，21 = extremely likely)',
            'answer1': 'Stars:0',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nMore stable software\r\nBetter screen display\r\nHigher storage capacity\r\nMore processing power\r\nBattery with longer duration',
            'question3': 'Which features would make you give the device a better rating? (Up to 16 max)',
            'answer3': "Because it is exceedingly slow doesn't work properly internet is so slow its unreal I regret buying this phone and in all honesty its only fit for the scrap"
        },
        {
            'id': 1914,
            'country': 'GB',
            'android_version': null,
            'cu': '5045D-2CALAE1-3',
            'imei': 'null',
            'model': '5045D',
            'create_time': '2018\/12\/9 00:39:14',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，22 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 17 max)',
            'answer3': null
        },
        {
            'id': 1915,
            'country': '364',
            'android_version': 'v7.0.1.2.0192.0',
            'cu': '5059A-2A5CBS1',
            'imei': '35445*****53567',
            'model': '5059A',
            'create_time': '2018\/12\/9 00:21:36',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，23 = extremely likely)',
            'answer1': 'Stars:8',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nBetter external materials and textures\r\nEasier to use software\r\nHigher storage capacity\r\nBetter audio quality',
            'question3': 'Which features would make you give the device a better rating? (Up to 18 max)',
            'answer3': 'I would like to see more health programs kids storytime'
        },
        {
            'id': 1916,
            'country': 'US',
            'android_version': null,
            'cu': '9203A-2AOFUS1',
            'imei': '01489*****09789',
            'model': '9203A',
            'create_time': '2018\/12\/9 00:14:23',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，24 = extremely likely)',
            'answer1': 'Stars:6',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'Its easy to handle.',
            'question3': 'Which features would make you give the device a better rating? (Up to 19 max)',
            'answer3': '\r\nMore processing power\r\nBetter camera quality?'
        },
        {
            'id': 1917,
            'country': 'GB',
            'android_version': null,
            'cu': '5045T-2CCYMY1',
            'imei': 'null',
            'model': '5045T',
            'create_time': '2018\/12\/9 00:05:55',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，25 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 20 max)',
            'answer3': null
        },
        {
            'id': 1918,
            'country': '639',
            'android_version': 'v7.0.1.2.0192.0',
            'cu': '5033X-2AVDKE1',
            'imei': '35627*****33319',
            'model': '5033X',
            'create_time': '2018\/12\/9 00:04:11',
            'status': '3',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，26 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 21 max)',
            'answer3': null
        },
        {
            'id': 1919,
            'country': 'AU',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '5009A-2ATSAU1',
            'imei': 'null',
            'model': '5009A',
            'create_time': '2018\/12\/8 23:40:11',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，27 = extremely likely)',
            'answer1': 'Stars:9',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nBetter screen display\r\nHigher storage capacity\r\nBattery with longer duration\r\nBetter audio quality',
            'question3': 'Which features would make you give the device a better rating? (Up to 22 max)',
            'answer3': 'First smart phone for me. Total noob. Found this device easy to get used to. Virtual keyboard a little hard to use. Large fingers! Prompt very good. Overall, very good!'
        },
        {
            'id': 1920,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0165.0',
            'cu': '5047Y-2ATWGB1-1',
            'imei': '35847*****90097',
            'model': '5047Y',
            'create_time': '2018\/12\/8 23:35:49',
            'status': '4',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，28 = extremely likely)',
            'answer1': 'Stars:1',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nBetter external materials and textures',
            'question3': 'Which features would make you give the device a better rating? (Up to 23 max)',
            'answer3': "Don't know what to say"
        },
        {
            'id': 1921,
            'country': 'GB',
            'android_version': null,
            'cu': '5010D-2BALWE1',
            'imei': 'null',
            'model': '5010D',
            'create_time': '2018\/12\/8 23:33:30',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，29 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': 'I really like the way the phone works n',
            'question3': 'Which features would make you give the device a better rating? (Up to 24 max)',
            'answer3': '\r\nEasier to use software\r\nBetter screen display\r\nHigher storage capacity\r\nBattery with longer duration\r\nBetter camera quality?'
        },
        {
            'id': 1922,
            'country': 'US',
            'android_version': null,
            'cu': '4055U-2AALAV1',
            'imei': '35364*****96860',
            'model': '4055U',
            'create_time': '2018\/12\/8 23:29:24',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，30 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 25 max)',
            'answer3': null
        },
        {
            'id': 1923,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0177.0',
            'cu': '4034X-2AE8GBA',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/8 23:29:01',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，31 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nExternal shape more attractive',
            'question3': 'Which features would make you give the device a better rating? (Up to 26 max)',
            'answer3': 'I was busy'
        },
        {
            'id': 1924,
            'country': 'IE',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '5099Y-2APZIE1',
            'imei': 'null',
            'model': '5099Y',
            'create_time': '2018\/12\/8 23:28:58',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，32 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nUpgradable Android version',
            'question3': 'Which features would make you give the device a better rating? (Up to 27 max)',
            'answer3': 'Lol'
        },
        {
            'id': 1925,
            'country': 'US',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '5099A-2BB8BS1',
            'imei': 'null',
            'model': '5099A',
            'create_time': '2018\/12\/8 23:18:49',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，33 = extremely likely)',
            'answer1': 'Stars:9',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nUpgradable Android version\r\nHigher storage capacity\r\nBattery with longer duration\r\nBetter audio quality\r\nBetter camera quality?',
            'question3': 'Which features would make you give the device a better rating? (Up to 28 max)',
            'answer3': "I thought it was going to suck honestly I didn't want anything that wasn't a Samsung. But the phone is such an upgrade from my Samsung it feels like my eyes just opened. It's truly great"
        },
        {
            'id': 1926,
            'country': 'AU',
            'android_version': 'v7.0.1.2.0163.2',
            'cu': '9008T-2AVDAU1',
            'imei': 'null',
            'model': '9008T',
            'create_time': '2018\/12\/8 23:04:12',
            'status': '3',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，34 = extremely likely)',
            'answer1': 'Stars:9',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nUpgradable Android version\r\nHigher storage capacity\r\nBattery with longer duration\r\nBetter audio quality\r\nBetter camera quality?',
            'question3': 'Which features would make you give the device a better rating? (Up to 29 max)',
            'answer3': '9'
        },
        {
            'id': 1927,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0177.0',
            'cu': '4034X-2AE8GBA',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/8 23:01:00',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，35 = extremely likely)',
            'answer1': 'Stars:5',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 30 max)',
            'answer3': null
        },
        {
            'id': 1928,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '4034X-2AALGBA-1',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/8 22:55:34',
            'status': '3',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，36 = extremely likely)',
            'answer1': 'Stars:7',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nMore processing power',
            'question3': 'Which features would make you give the device a better rating? (Up to 31 max)',
            'answer3': 'The device is very slow to respond to touch.'
        },
        {
            'id': 1929,
            'country': '505',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '5009A-2CTSAU1',
            'imei': '35539*****73976',
            'model': '5009A',
            'create_time': '2018\/12\/8 22:16:20',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，37 = extremely likely)',
            'answer1': 'Stars:0',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nExternal shape more attractive\r\nLess weight \/ thickness',
            'question3': 'Which features would make you give the device a better rating? (Up to 32 max)',
            'answer3': "Horrible. It just shuts of 24\/7 doesn't run anything and the finger scanner is trash"
        },
        {
            'id': 1930,
            'country': 'US',
            'android_version': null,
            'cu': '8050E-2AALPH1',
            'imei': '01457*****49778',
            'model': '8050E',
            'create_time': '2018\/12\/8 22:05:08',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，38 = extremely likely)',
            'answer1': 'Stars:2',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 33 max)',
            'answer3': null
        },
        {
            'id': 1931,
            'country': '366',
            'android_version': 'v7.0.1.2.0191.0',
            'cu': '5033A-2CCIJM1',
            'imei': '35626*****05884',
            'model': '5033A',
            'create_time': '2018\/12\/8 21:26:54',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，39 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 34 max)',
            'answer3': null
        },
        {
            'id': 1932,
            'country': 'AU',
            'android_version': 'v7.0.1.2.0163.2',
            'cu': '9008T-2AVDAU1',
            'imei': 'null',
            'model': '9008T',
            'create_time': '2018\/12\/8 21:17:56',
            'status': '3',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，40 = extremely likely)',
            'answer1': 'Stars:10',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nMore stable software\r\nBattery with longer duration\r\nBetter after sales service',
            'question3': 'Which features would make you give the device a better rating? (Up to 35 max)',
            'answer3': null
        },
        {
            'id': 1933,
            'country': 'US',
            'android_version': null,
            'cu': '5045X-2DWNIT3',
            'imei': 'null',
            'model': '5045X',
            'create_time': '2018\/12\/8 21:14:52',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，41 = extremely likely)',
            'answer1': 'Stars:7',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 36 max)',
            'answer3': null
        },
        {
            'id': 1934,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0166.0',
            'cu': '5044Y-2ATBMK1',
            'imei': 'null',
            'model': '5044Y',
            'create_time': '2018\/12\/8 21:14:11',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，42 = extremely likely)',
            'answer1': 'Stars:5',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nExternal shape more attractive\r\nUpgradable Android version\r\nHigher storage capacity\r\nBetter audio quality',
            'question3': 'Which features would make you give the device a better rating? (Up to 37 max)',
            'answer3': null
        },
        {
            'id': 1935,
            'country': 'NZ',
            'android_version': null,
            'cu': '4034X-2B1NNZ1',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/8 21:11:12',
            'status': '1',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，43 = extremely likely)',
            'answer1': 'Stars:4',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': null,
            'question3': 'Which features would make you give the device a better rating? (Up to 38 max)',
            'answer3': '\r\nBattery with longer duration'
        },
        {
            'id': 1936,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '4034X-2APWGBA',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/8 21:06:51',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，44 = extremely likely)',
            'answer1': 'Stars:0',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nMore stable software\r\nHigher storage capacity\r\nBattery with longer duration',
            'question3': 'Which features would make you give the device a better rating? (Up to 39 max)',
            'answer3': 'This phone is too slow on speed and I have to delete items to make it work properly.'
        },
        {
            'id': 1937,
            'country': '530',
            'android_version': 'v7.0.1.2.0192.0',
            'cu': '5033T-2AVDNZ1',
            'imei': '35626*****72091',
            'model': '5033T',
            'create_time': '2018\/12\/8 21:06:18',
            'status': '2',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，45 = extremely likely)',
            'answer1': 'Stars:8',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nExternal shape more attractive\r\nBetter external materials and textures\r\nLess weight \/ thickness\r\nBetter screen display\r\nBetter camera quality?',
            'question3': 'Which features would make you give the device a better rating? (Up to 40 max)',
            'answer3': 'I could give a 100% rating if you like '
        },
        {
            'id': 1938,
            'country': 'GB',
            'android_version': 'v7.0.1.2.0189.0',
            'cu': '4034X-2AALGBA',
            'imei': 'null',
            'model': '4034X',
            'create_time': '2018\/12\/8 20:58:31',
            'status': '3',
            'question1': 'How likely is it that you would recommend our device to a colleague or friend? (Touch the slider below to select an answer. On a scale from 0 to 10 where 0 = not at all likely，46 = extremely likely)',
            'answer1': 'Stars:1',
            'question2': 'Why did you rate our device this way? (Optional)',
            'answer2': '\r\nEasier to use software\r\nHigher storage capacity\r\nMore processing power\r\nBattery with longer duration\r\nBetter after sales service',
            'question3': 'Which features would make you give the device a better rating? (Up to 41 max)',
            'answer3': "Its the worse phone I've ever owned its slow and\n\n often doesn't do anything when you press the keyboard .I could go on . nothing good about this phone."
        }
    ]
};

actions.loadList = (pageNo, pageSize) => (dispatch, getState) => {
    dispatch({ type: 'CARE_SURVEY_ONLINE_LOADING', loading: true });
    const state = getState()['care_survey_online'];
    const page = state.page;
    const params = state.searchParams;
    let list = [];
    for (let i = 0; i < 10; i++) {
        list.push(mockData.RECORDS[Math.floor((Math.random() * 25))]);
    }
    return ajax.get('/care_survey_online', {
        pageNo: pageNo || page.pageNo,
        pageSize: pageSize || page.pageSize
    }).then((data) => {
        dispatch({ type: 'CARE_SURVEY_ONLINE_LOADING', loading: false });
        dispatch({
            type: 'CARE_SURVEY_ONLINE_LOAD',
            pageNo: pageNo || data.pageNo,
            pageSize: data.pageSize,
            dataCount: data.totalCount,
            list: list
        });
    });
};

export default actions;
